/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Which operational decision the agent made.
 */
export type DecisionType = "tip" | "timing" | "retry";

/**
 * An AI decision with the full reasoning trace required for judge-visible "AI Demonstration".
 */
export interface Decision {
  /**
   * Short, human-readable action (e.g. `"tip 12000->18000 lamports"`).
   */
  action: string;
  /**
   * State after the decision, if applicable.
   */
  after?: {
    [k: string]: unknown;
  };
  /**
   * State before the decision (for before/after comparison), if applicable.
   */
  before?: {
    [k: string]: unknown;
  };
  /**
   * Confidence in `[0,1]`.
   */
  confidence: number;
  decision_type: DecisionType;
  /**
   * Structured snapshot of the inputs the agent considered.
   */
  inputs_considered: {
    [k: string]: unknown;
  };
  /**
   * How long the decision took (ms) — observability for the AI path.
   */
  latency_ms: number;
  /**
   * Which provider produced the decision (`anthropic` | `openai` | `ollama`).
   */
  provider: string;
  /**
   * The model's reasoning for this decision.
   */
  reasoning: string;
  ts: string;
  [k: string]: unknown;
}
