/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The single telemetry envelope. `kind` tags the variant on the wire.
 */
export type TelemetryEvent =
  | {
      kind: "slot";
      parent?: number | null;
      slot: number;
      status: SlotStatus;
      ts: string;
      [k: string]: unknown;
    }
  | {
      /**
       * 1-indexed attempt number within `base_id` (attempt 1 is the first try; ≥2 are retries).
       */
      attempt?: number | null;
      /**
       * The logical bundle this attempt belongs to — retries of the same bundle share a `base_id`. This lets the lifecycle-log export chain a failed attempt to its recovered resubmission (the AI recovery unit). Optional for backward compatibility with telemetry emitted before this field.
       */
      base_id?: string | null;
      bundle_id: string;
      kind: "bundle";
      phase: BundlePhase;
      region: string;
      signatures: string[];
      tip_account: string;
      tip_lamports: number;
      ts: string;
      [k: string]: unknown;
    }
  | {
      event: LifecycleEvent;
      id: string;
      kind: "lifecycle";
      [k: string]: unknown;
    }
  | {
      classification: FailureClassification;
      id: string;
      kind: "failure";
      [k: string]: unknown;
    }
  | {
      avg_confirmed_latency_ms?: number | null;
      bundle_landing_probability: number;
      confirm_latency_variance_ms?: number | null;
      congestion_score: number;
      cost_per_successful_landing?: number | null;
      kind: "health";
      retry_success_rate: number;
      slot_stability_score: number;
      tip_efficiency_ratio: number;
      tip_floor_lamports: number;
      ts: string;
      [k: string]: unknown;
    }
  | {
      /**
       * Short, human-readable action (e.g. `"tip 12000->18000 lamports"`).
       */
      action: string;
      /**
       * State after the decision, if applicable.
       */
      after?: {
        [k: string]: unknown;
      };
      /**
       * State before the decision (for before/after comparison), if applicable.
       */
      before?: {
        [k: string]: unknown;
      };
      /**
       * Confidence in `[0,1]`.
       */
      confidence: number;
      decision_type: DecisionType;
      /**
       * Structured snapshot of the inputs the agent considered.
       */
      inputs_considered: {
        [k: string]: unknown;
      };
      kind: "decision";
      /**
       * How long the decision took (ms) — observability for the AI path.
       */
      latency_ms: number;
      /**
       * Which provider produced the decision (`anthropic` | `openai` | `ollama`).
       */
      provider: string;
      /**
       * The model's reasoning for this decision.
       */
      reasoning: string;
      ts: string;
      [k: string]: unknown;
    };
/**
 * Slot lifecycle status as surfaced by the Yellowstone slots subscription.
 *
 * Ordering of the variants follows the real progression of a healthy slot: `FirstShredReceived → CreatedBank → Completed → Processed → Confirmed → Finalized`, with `Dead` as the off-ramp for a slot whose bank was abandoned (forked out).
 *
 * The first three ("inter-slot") statuses are gated behind the provider's `interslot_updates` support; the engine must degrade gracefully to the commitment statuses when they are absent (flagged for experimental verification against the configured provider).
 */
export type SlotStatus =
  | "first_shred_received"
  | "created_bank"
  | "completed"
  | "processed"
  | "confirmed"
  | "finalized"
  | "dead";
/**
 * Phase of a bundle's submission, for the bundle telemetry stream.
 */
export type BundlePhase = "submitted" | "acked" | "status_update";
/**
 * A stage in one submission's lifecycle.
 */
export type LifecycleStage = "submitted" | "processed" | "confirmed" | "finalized" | "failed" | "expired" | "dropped";
/**
 * The taxonomy class of a failure.
 */
export type FailureClass =
  | "expired_blockhash"
  | "fee_too_low"
  | "compute_exceeded"
  | "bundle_failure"
  | "leader_miss"
  | "skipped_slot"
  | "duplicate_signature"
  | "instruction_error"
  | "confirmation_timeout"
  | "unclassified";
/**
 * Whether a classification is directly observed or inferred from a pattern of signals.
 */
export type EvidenceGrade = "observable" | "inferred";
/**
 * Which operational decision the agent made.
 */
export type DecisionType = "tip" | "timing" | "retry";

/**
 * One recorded lifecycle transition.
 */
export interface LifecycleEvent {
  /**
   * Milliseconds since the previous recorded event (`None` for the first, Submitted).
   */
  delta_ms_from_prev?: number | null;
  /**
   * Slot associated with the stage (absent for some failures like pre-inclusion expiry).
   */
  slot?: number | null;
  stage: LifecycleStage;
  ts: string;
  [k: string]: unknown;
}
/**
 * A classification result with confidence, grade, retryability, and a human-readable rationale.
 */
export interface FailureClassification {
  class: FailureClass;
  confidence: number;
  grade: EvidenceGrade;
  rationale: string;
  retryable: boolean;
  [k: string]: unknown;
}
